name: TravelStride CI/CD

on:
  push:
    branches: [ main, dev ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (force clean & update)
        run: mvn clean package -U -DskipTests

      - name: Check built JAR file (confirm file exists and timestamp)
        run: |
          ls -lh target/TravelStride-0.0.1-SNAPSHOT.jar
          file target/TravelStride-0.0.1-SNAPSHOT.jar

      - name: Backup old JAR on VPS (for rollback)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /root/travel/Tralvel/backup/
            if [ -f /root/travel/Tralvel/target/TravelStride-0.0.1-SNAPSHOT.jar ]; then
              cp /root/travel/Tralvel/target/TravelStride-0.0.1-SNAPSHOT.jar /root/travel/Tralvel/backup/TravelStride-$(date +"%Y%m%d%H%M%S").jar
              echo "Backup completed!"
            fi

      - name: Deploy JAR to VPS using password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: target/TravelStride-0.0.1-SNAPSHOT.jar
          target: /root/travel/Tralvel/target/

      - name: SSH pull latest code on VPS (if needed) and restart app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export PATH=$PATH:/usr/local/bin
            echo "== Pull latest code if git folder exists =="
            if [ -d /root/travel/Tralvel ]; then
              cd /root/travel/Tralvel
              if [ -d .git ]; then
                git pull origin main || true
              fi
            fi

            echo "== Deploy new JAR =="
            cd /root/travel/Tralvel/target/
            ls -lh TravelStride-0.0.1-SNAPSHOT.jar

            echo "== Restart PM2 App =="
            pm2 delete travel-app || true
            pm2 start java --name travel-app -- -jar TravelStride-0.0.1-SNAPSHOT.jar --server.port=8080
      - name: Notify Telegram Success
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ TravelStride CI/CD Deploy Success on *${{ github.ref_name }}* branch 🚀" \
          -d parse_mode=Markdown
