name: TravelStride CI/CD

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS, pull code, build and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "== Check current working directory =="
            pwd

            # Navigate to the correct directory
            cd ~/Travel/BE/Tralvel

            # Ensure the JAR exists before continuing
            echo "== Check if JAR file exists in target/ =="
            ls target/

            echo "== Pull latest code =="
            git pull origin product

            echo "== Build new JAR =="
            mvn clean package -U -DskipTests

            # Check if the JAR file exists after build
            if [ ! -f target/TravelStride-0.0.1-SNAPSHOT.jar ]; then
              echo "Error: JAR file not found!"
              exit 1
            fi

            echo "== Backup old JAR =="
            mkdir -p backup
            cp target/TravelStride-0.0.1-SNAPSHOT.jar backup/TravelStride-$(date +"%Y%m%d%H%M%S").jar

            echo "== Restart travel-app using PM2 =="
            pm2 stop travel-app || true
            pm2 delete travel-app || true
            pm2 start target/TravelStride-0.0.1-SNAPSHOT.jar --name travel-app -- --server.port=3082

      - name: Notify Telegram Success
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Dai Dev Try CI/CD Build and Deploy thành công trên *${{ github.ref_name }}* 🚀" \
          -d parse_mode=Markdown
