name: TravelStride CI/CD

on:
  push:
    branches: [ main, dev ]  # Thêm dev nếu cần test

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (force clean & update)
        run: mvn clean package -U -DskipTests

      - name: Check built JAR file (confirm file exists and timestamp)
        run: |
          ls -lh target/TravelStride-0.0.1-SNAPSHOT.jar
          file target/TravelStride-0.0.1-SNAPSHOT.jar

      - name: Deploy JAR to VPS using password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: target/TravelStride-0.0.1-SNAPSHOT.jar
          target: /root/travel/Tralvel/target/

      - name: SSH restart app using password + check jar time
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export PATH=$PATH:/usr/local/bin
            cd /root/travel/Tralvel/target/
            echo "==== JAR file info ===="
            ls -lh TravelStride-0.0.1-SNAPSHOT.jar
            echo "======================="
            pm2 delete travel-app || true
            pm2 start java --name travel-app -- -jar TravelStride-0.0.1-SNAPSHOT.jar --server.port=8080
